# Generated by Django 4.1.5 on 2023-08-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
