# Generated by Django 4.1.5 on 2023-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('diabetes_status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('diabetes_type', models.CharField(blank=True, choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Type 3', 'Type 3'), ('Type 4', 'Type 4')], max_length=10, null=True)),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='patient_images/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='patient_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
