# Generated by Django 4.2.4 on 2023-09-14 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
