# Generated by Django 4.2.4 on 2023-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_patient_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='credit_val',
            field=models.IntegerField(default=10),
        ),
    ]
