# Generated by Django 4.2.4 on 2023-09-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_doctor_credit_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='credit_val',
            field=models.IntegerField(default=5),
        ),
    ]
