# Generated by Django 4.2.4 on 2023-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_doctor_credit_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='credit_val',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diabetes_type',
            field=models.CharField(blank=True, choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/patient_images'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/patient_images'),
        ),
    ]
