# Generated by Django 4.2.4 on 2023-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_doctor_credit_val_alter_patient_diabetes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/patient_images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/patient_images/'),
        ),
    ]
