# Generated by Django 4.2.4 on 2023-09-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_patient_left_image_alter_patient_right_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/patient_images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/patient_images/'),
        ),
    ]
