# Generated by Django 4.2.4 on 2023-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
