# Generated by Django 4.2.4 on 2023-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_creditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
